# BowSound Configuration File

# will send to launched player and hit the projectile
# not to send, set to false
#
# Replacement
# %hp      : hit player's health
# %bhp     : player's health before hit
# %rawname : player's name (no tag)
# %name    : player's display name

hit-message: "§dHIT §e-> §b%name §7(§aHP: §e%hp§7)"